### ISSUE TITLE
more real `.has` method?

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/cache-base#2]
Before was using `has-value(s)`, now is just `typeof val !== undefined`

also add `hasOwn` and `union` methods?

**Comment by jonschlinkert** [comment]
this approach passed all of the tests of the other `.has` method, since it was effectively doing the same thing (at least in non-edge-cases).

> add hasOwn and union methods?

I was just thinking the same thing about `union` today - I just refactored `base-data` and could have used it. we can add `union` but let me think about `.hasOwn`. Honestly I almost always use `.get` because I can get the same answer and use the resulting value if I need it, instead of doing two lookups (`.has` then `.get`)

**Comment by tunnckoCore** [comment]
> Honestly I almost always use .get

Mm yea, me too. But it's logical to have. I think it can be in help for some users that don't got the things as we got it.

**Comment by tunnckoCore** [comment]
@jonschlinkert ping about the hasOwn and has.
